require("LiamGoodacre.setting").setup()
require("LiamGoodacre.plugin").setup()
require("LiamGoodacre.theme").setup()
require("LiamGoodacre.tooling").setup()
require("LiamGoodacre.util").setup_modules("LiamGoodacre.commands")
require("LiamGoodacre.util").setup_modules("LiamGoodacre.mappings")
require("LiamGoodacre.language").setup()
require("LiamGoodacre.dashboard").setup()
