require("LiamGoodacre.setting").setup()
require("LiamGoodacre.plugin").setup()
require("LiamGoodacre.theme").setup()
require("LiamGoodacre.command").setup()
require("LiamGoodacre.mapping").setup()
require("LiamGoodacre.language").setup()
