require("LiamGoodacre.setting").setup()
require("LiamGoodacre.plugin").setup()
require("LiamGoodacre.theme").setup()
require("LiamGoodacre.util").setup_modules("LiamGoodacre.commands")
require("LiamGoodacre.mapping").setup()
require("LiamGoodacre.util").setup_modules("LiamGoodacre.languages")
